<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($data) {

        $query = $this->createQueryBuilder('c');

        // sortowanie
        if(isset($data['sort'])) {
            $params = explode('.', $data['sort']);

            if (isset($params[1])) {
                $query->orderBy('c.'.$params[0], $params[1]);
            } else {
                $query->orderBy('c.'.$params[0]);
            }

        } else {
            $query->orderBy('c.position', 'ASC');
        }

        return $query->getQuery()->getResult();
    }

    public function getTotalCategories() {
        return $this->createQueryBuilder('c')
            ->select('COUNT(c.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
