<?php

namespace AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($data, $page = 1) {

        $query = $this->createQueryBuilder('t');

        // sortowanie

        if(!empty($data['sort'])) {
            $params = explode('.', $data['sort']);

            if (isset($params[1])) {
                $query->orderBy('t.'.$params[0], $params[1]);
            } else {
                $query->orderBy('t.'.$params[0]);
            }

        } else {
            $query->orderBy('t.id', 'ASC');
        }

        // paginacja

        $offset = ($page * 10) - 10;

        $query->setFirstResult($offset)
            ->setMaxResults(10);

        return $query->getQuery()->getResult();
    }

    public function getTotalTags() {
        return $this->createQueryBuilder('t')
            ->select('COUNT(t.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
