security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        user:
            entity: { class: AppBundle:User, property: email }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:   ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: /category/
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: homepage
            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                domain: ~
    access_control:
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/, role: ROLE_USER }